#!/bin/bash

#set -x
 
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Counter for vulnerabilities
vulnerabilities=0

# Declare associative array containing regular expressions (it's going to be expanded in future)
declare -A regexp_list
regexp_list[AWS_Access_Key]='[A-Z0-9]{20}'
regexp_list[AWS_Secret_Key]='[A-Za-z0-9/+=]{40}'
regexp_list[Password]='(.*)([p|P][a|A][s|S][s|S][w|W][o|O][r|R][d|D])([^*|false|true].*){5,256}'
regexp_list[Secret_URLs]='http(.?)://((api).(.*).(.*){1,256})'
regexp_list[Email_address]='(.*)([A-Za-z0-9_\.\-]{1,256}@[A-Za-z0-9\.\-]{1,256}.[A-Za-z0-9\.]{2,6})'


 
# Redirect output to stderr.
exec 1>&2


for i in "${!regexp_list[@]}"
do
 ## Check changed files
 KEY=$(git diff --cached --name-only -z $against | xargs -0 cat | grep -c -E ${regexp_list[$i]})

 #KEY_ID=$(cat /home/abondar/projects/telstra/git/15062016/secure/scripts/README | grep -c -E '[A-Z0-9]{20}')
 #KEY=$(cat /home/abondar/projects/telstra/git/15062016/secure/scripts/README | grep -c -E ${regexp_list[$i]})
 #echo "$i :  ${regexp_list[$i]}"
 #echo "key :  $KEY"
 if [ $KEY -ne 0 ]; then
  echo "Found patterns for ${i}"
  echo "Please check your code"
  ((vulnerabilities++))
 else
  echo "Patterns for ${i} are not found"
 fi
done

echo "Number of vulnerabilities :  $vulnerabilities"
 
if [ $vulnerabilities -ne 0 ]; then
    echo "Commit is rejected."
    exit 1
fi
 
# Normal exit
exit 0

